### ISSUE TITLE
Add button hints

### ISSUE THREAD

**Issue by skodapetr** [Jkuzz/sparql-explorer#32]
Add hints to buttons. For example what "More classes" at the Flow page do. May be "Load additional 10 classes with most instances".

**Comment by Jkuzz** [comment]
Added support for button tooltips:
![image](https://user-images.githubusercontent.com/68104924/232305407-e63a0594-fc87-4502-91bf-ebfcd77b35b7.png)
Are there any more places where tooltips are needed
