### ISSUE TITLE
Fix occurance

### ISSUE THREAD

**Issue by skodapetr** [Jkuzz/sparql-explorer#42]
Fix or rename as now it can be > 100% like for https://data.gov.cz/sparql

![image](https://user-images.githubusercontent.com/3341693/231128873-40eadeb0-e4d2-43d3-a7b8-8109dfc6caf2.png)

**Comment by Jkuzz** [comment]
I'm not really sure how to handle this. In this case there are on average >17 labels for each entity.
Maybe rename to "Prevalence" or "Frequency"?
